### ISSUE TITLE
Collaborator request 

### ISSUE THREAD

**Issue by tmishina** [ComplianceAsCode/auditree-arboretum#11]
I would like collaborator (write) access to this repository, so I can contribute
to the Auditree Arboretum library.

 - [x] I have read the [contributing guidelines][CONTRIBUTING]

[CONTRIBUTING]: https://github.com/ComplianceAsCode/auditree-arboretum/blob/master/CONTRIBUTING.md

**Comment by alfinkel** [comment]
granted

**Comment by tmishina** [comment]
@alfinkel I (`tmishina`) am still not a collaborator of this repository, and failed to push my branch to the repository.
Could you add me to the collaborator list? 
(also, I cannot reopen the issue...)

**Comment by alfinkel** [comment]
You need to accept the invite.  It should be in your email.

<img width="982" alt="Screen Shot 2020-08-12 at 7 30 33 AM" src="https://user-images.githubusercontent.com/8793303/90015159-d5848800-dc6d-11ea-8784-f92ca66d9c1a.png">

**Comment by tmishina** [comment]
Sorry, the invitation email was gone outside of the github folder of my mailbox...I found it and accepted your invitation.  I can now push branches.  Thank you.
