### ISSUE TITLE
Collaborator request

### ISSUE THREAD

**Issue by Parthakumar-Roy** [ComplianceAsCode/auditree-arboretum#29]
I would like collaborator (write) access to this repository, so I can contribute
to the Auditree Arboretum library.

 - [x] I have read the [contributing guidelines][CONTRIBUTING]

[CONTRIBUTING]: https://github.com/ComplianceAsCode/auditree-arboretum/blob/master/CONTRIBUTING.md

**Comment by alfinkel** [comment]
Sorry @Parthakumar-Roy, clearly we need to update our CONTRIBUTING.md.  In PR #30 now.  See: https://github.com/ComplianceAsCode/auditree-arboretum/blob/058afc9ce2abef7359cf91cb293edaa911bf6293/CONTRIBUTING.md

For now just fork the repo and submit PR that way.  Thanks.
