### ISSUE TITLE
Use get_historical_evidence helper in checks

### ISSUE THREAD

**Issue by alfinkel** [ComplianceAsCode/auditree-arboretum#35]
## Overview

Once the ComplianceCheck.get_historical_evidence lands in the framework, we should change all uses of `self.locker.get_evidence` in the checks in this repo to `self.get_historical_evidence`.  This will ensure that historical evidence metadata is stored as part of the report metadata and check_results.json.

## Requirements

- Update Abandoned Evidence check
- Update Python Packages check
- Update Locker Repo Integrity check

## Approach

Switch uses of self.locker.get_evidence to self.get_historical_evidence

## Security and Privacy

N/A

## Test Plan

- All checks should run as before
- index.json for reports generated by those checks should now include historical evidence metadata
- check_results.json should now include historical evidence metadata for those checks

**Comment by alfinkel** [comment]
"get_historical_evidence" functionality currently in PR https://github.com/ComplianceAsCode/auditree-framework/pull/71

**Comment by drsm79** [comment]
I wonder if we do this, we shouldn't also add a helper method like `self.get_last_evidence()` instead of `self.locker.get_evidence`?

**Comment by alfinkel** [comment]
I think a `self.get_last_evidence()` would be redundant to the `with_raw_evidences` decorator and the `evidences` context manager.  Using either of those ensures we perform a TTL validation and that the evidence gets stored as part of the report metadata.  We don't have something comparable for historical evidence so we've been using `self.locker.get_evidence` in checks that need historical evidence.  The problem there is that it doesn't store the evidence in the reports metadata.  Adding get_historical_evidence to the check remedies that.  I could have updated `with_raw_evidences` and `evidences` to handle historical evidence but I thought that this was the less disruptive change.
