### ISSUE TITLE
New feature: Github source code repos permissions check

### ISSUE THREAD

**Issue by mic67mel** [ComplianceAsCode/auditree-arboretum#58]
## Overview

Provide a check to control the access to Github repositories containing source code. Permission access should be done at the team level, and not by adding single collaborators outside of team membership. 
This can be done through a check that alerts if there are single collaborators instead of teams and also alerts about forks of the source code repos.

## Requirements

- Based on the evidence collected by the existing fetcher [here](https://github.com/ComplianceAsCode/auditree-arboretum/blob/main/arboretum/permissions/fetchers/github/fetch_org_permissions.py)

For each Github repo containing source code :

- check that all the collaborators are defined as teams and no single collaborator outside of a Github team are added to the list.
- alert if any of the collaborators is detected to be a single user instead of a team.
- check if there are forks of the source code repos
- alert if there are forks of the source code repos

## Approach

Implement a permissions check which includes a report template to render the results.  Each single collaborator found in a repo will be considered a failure and reported with the following information grouped by repository:

* GitHub User
* A flag indicating if the single collaborator is an organization member

The permissions check reports on each fork found in a repo. Each fork found in a repo will be considered as a warning and reported with the following information grouped by repository:

* Fork URL

As additional information the permissions check also lists the organization teams as successes.

## Security and Privacy

N/A
## Test Plan

TBD

**Comment by alfinkel** [comment]
Seems like this can be closed now.
